name: Generate Card

on: 
    workflow_dispatch:
    schedule:
        - cron: '0 0,12 * * *'
permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v3.1.4
          
        - name: Install Edge
          uses: browser-actions/setup-edge@v1
          
        - name: Download Requirements
          run: pip install -r requirements.txt

        - name: Run
          run: |
            py generate.py --cookie "${{ secrets.COOKIE }}" --uid ${{ vars.UID }}
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add out.png || echo
            # "echo" returns true so the build succeeds, even if no changed files
            git commit -m 'actions: update generated files' || echo
            git push
          shell: bash
